exports.ANALYTICS = {
  TILE_DATA: '/api/v2/searchOverview/getTileData',
  SUMMARY_CHART_DATA: '/api/v2/searchOverview/getSearchSummaryChart',
  ALL_SEARCH_QUERY: '/api/v2/searchQuery/all',
  SEARCHQUERY_WITH_RESULT: '/api/v2/searchQuery/withResults',
  SEARCHQUERY_WITH_NO_CLICKS: '/api/v2/searchQuery/withNoClicks',
  SEARCHQUERY_WITHOUT_RESULT: '/api/v2/searchQuery/withoutResults',
  SEARCHQUERY_HISTOGRAM: '/api/v2/searchQuery/histogram',
  MISSED_QUERY_HISTOGRAM: '/api/v2/searchQuery/missedQueryHistogram',
  SEARCH_SESSION_BY_CASE_UID_AUTH: '/api/v2/searchSession/byCaseUidAuth',
  ALL_SEARCH_CONVERSION: '/api/v2/searchConversion/all',
  SEARCH_CONVERSION_NOT_FIRST_PAGE: '/api/v2/searchConversion/notOnFirstPage',
  SEARCH_CONVERSION_WITH_FILTERS: '/api/v2/searchConversion/withFilters',
  SEARCH_CONVERSION_BY_SESSION_ID: '/api/v2/searchConversion/bySessionsId',
  DISCUSSION_READY_TO_BECOM_ARTICLE: '/api/v2/searchConversion/DiscussionsReadyToBecomeArticles',
  SEARCH_SESSION_BY_SESSION_ID: '/api/v2/searchSession/bySearchSessionId',
  ALL_SEARCH_QUERY_WITH_SESSION: '/api/v2/searchSession/all/searchQuery',
  KCS_SUPPORT: '/api/v2/searchQuery/kcsSupport',
  SEARCH_SESSION_BY_CASE_UID: '/api/v2/searchSession/byCaseUid',
  ARTICLE_CREATED_CASES: '/api/v2/conversion/articlesCreatedCases',
  ARTICLE_CREATED_CASES_SESSIONS: '/api/v2/conversion/articlesCreatedCasesSessions',
  SEARCHES_CREATED_CASE: '/api/v2/conversion/searchesCreatedCase',
  ARTICLE_DEFLECTED_CASES: '/api/v2/conversion/articlesDeflectedCase',
  SEARCHES_ON_DEFLECTION: '/api/v2/conversion/searchesOnDeflection',
  ATTACHED_ARTICLE: '/api/v2/conversion/attachedArticles',
  ATTACHED_ON_CASE: '/api/v2/conversion/attachedOnCase',
  AVERAGE_CLICK_POSITION: '/api/v2/overview/averageClickPositionChart',
  OVERVIEW_SEARCH_CLICK_POSITION: '/api/v2/overview/searchClickPosition',
  OVERVIEW_CREATED_CASES: '/api/v2/overview/createdCases',
  OVERVIEW_FEATURED_SNIPPET: '/api/v2/overview/featuredSnippet',
  OVERVIEW_KNOWLEDGE_TITLE: '/api/v2/overview/knowledgeTitle',
  OVERVIEW_PAGE_RATING: '/api/v2/overview/pageRating',
  OVERVIEW_SEARCH_FEEDBACK: '/api/v2/overview/searchFeedback',
  OVERVIEW_ADVERTISEMENTS: '/api/v2/overview/advertisements',
  LLM_RESPONSE_FEEDBACK: '/api/v2/llm/llm-response-feedback',
  TILE_DATA_CONTENT: '/api/v2/content/tileDataContent',
  SPLIT_TILE_DATA_CONTENT: '/api/v2/content/splitTileDataContent',
  UNSUCCESSFUL_SUMMARY_CHART: '/api/v2/content/unSuccessfulSummaryChart',
  SEARCHS_WITH_NO_CLICKS: '/api/v2/overview/searchsWithNoClicks',
  SUCCESSIVE_NO_CLICKS: '/api/v2/content/succesiveNoClicks',
  SEARCHES_WITH_NO_RESULT: '/api/v2/overview/searchesWithNoResult',
  SUCCESSIVE_NO_RESULTS: '/api/v2/content/succesiveNoResults',
  UNSUCCESSFUL_SEARCH_SESSION_CHART: '/api/v2/content/unSuccessfulSearchSessionChart',
  HIGH_CONVERSION: '/api/v2/content/highConversion',
  HIGH_CONVERSION_CLICKS: '/api/v2/content/highConversionClicks',
  HIGH_CONVERSION_SESSIONS: '/api/v2/content/highConversionSessions',
  ARTICLE_USAGE_BY_AGENTS: '/api/v2/content/articleUsageByAgents',
  SUCCESSIVE_ARTICLES_USAGE: '/api/v2/content/successiveArticlesUsage',
  TILE_DATA_METRICS_1: '/api/v2/overview/tileDataMetrics1',
  TILE_DATA_METRICS_2: '/api/v2/overview/tileDataMetrics2',
  SESSION_LOG: '/api/v2/session/log/all',
  SESSION_LIST_TABLE: '/api/v2/session/list/table',
  CASE_DEFLECTION_STAGE_1: '/api/v2/conversion/caseDeflectionStage1',
  CASE_DEFLECTION_STAGE_2: '/api/v2/conversion/caseDeflectionStage2',
  CASE_DEFLECTION_TRENDS: '/api/v2/conversion/caseDeflectionTrends',
  CONVERSION_SUMMARY: '/api/v2/conversion/conversionSummary',
  CURRENT_RELEVANCE_INDEX: '/api/v2/conversion/current-relevance-index',
  RELEVANCE_INDEX: '/api/v2/conversion/relevance-index',
  LEADERSHIP_UNASSISTED_SELF_SOLVE_VOLUME: '/leadership/unassisted-self-solve-volume',
  LEADERSHIP_ASSISTED_SELF_SOLVE_VOLUME: '/leadership/assisted-self-solve-volume',
  LEADERSHIP_ASSISTED_CASE_VOLUME: '/leadership/assisted-case-volume',
  LEADERSHIP_DEFLECTION_COUNT: '/leadership/deflection-count',
  LEADERSHIP_DEFLECTION_COST_SAVINGS_DOWNLOAD: '/leadership/deflection-cost-savings-download',
  LEADERSHIP_GET_CONTENT_SOURCES: '/leadership/get-content-sources',
  CLICKS_COUNT_CONTENT_SOURCE: '/api/v2/conversion/clicksCountContentSource',
  CONVERSION_SESSION_DETAILS: '/api/v2/conversion/sessionDetails',
  CONVERSION_TOP_CLICKED_DOCS: '/api/v2/conversion/topClickedDocs',
  CONVERSION_SEARCHES_ON_CLICK: '/api/v2/conversion/searchesOnClick',
  CONVERSION_TOP_SEARCHES_WITH_CLICKS: '/api/v2/conversion/topSearchesWithClicks',
  CONVERSION_CLICKED_RESULTS: '/api/v2/conversion/clickedResults',
  CONVERSION_LINK_SHARING: '/api/v2/conversion/linkSharing',
  CONVERSION_DISCUSSIONS: '/api/v2/conversion/discussions',
  SESSION_TRACKING_FORMATTED: '/api/v2/getSessionTrackingFormattedResult'
};

exports.AUTH_API = {
  TOKEN: '/oauth/token'
};

exports.SEARCH_API = {
  SEARCH: '/api/v2_search/searchResults',
  GPT_RESULTS: '/api/v2_gpt/gptResults'
};

exports.CONTENT_API = {
  CONTENT_SOURCES: '/api/v2_cs/contentSource/all',
  CONTENT_SOURCES_BY_ID: '/api/v2_cs/contentSource',
  OBJECT_AND_FIELDS: '/api/v2_cs/contentSource/<contentSourceId>/objectAndFields',
  OBJECT_DATA: '/api/v2_cs/apiData/contentSource/<contentSourceId>/object/<objectId>/get',
  OBJECT_DATA_WITH_ID: '/api/v2_cs/apiData/contentSource/<contentSourceId>/object/<objectId>/document/<documentId>/get',
  UPDATE_DOC_BY_ID: '/api/v2_cs/apiData/contentSource/<contentSourceId>/object/<objectId>/document/<documentId>/update',
  BATCH_UPLOAD: '/api/v2_cs/apiData/contentSource/<contentSourceId>/object/<objectId>/bulkUpload',
  SEARCH_CLIENTS: '/api/v2/search-clients'
};
